### ISSUE TITLE
Links to Apps at the top & font change

### ISSUE THREAD

**Issue by genvagula** [Openworx/backend_theme#11]
Hi,

First i'd like to thank you for this awesome theme !

Had just a few questions.

First is there a way to put links to the top bar ? (back as it was in the basic theme)

Where is the part of the code defining the font ? I'd like to change it to my likings.

Thanks again and cheers,
Gen

**Comment by Yakulu** [comment]
> First is there a way to put links to the top bar ? (back as it was in the basic theme)

Note sure I undertstand correctly but top bar links are similar to classic secondary menus. So you "just" have to add and edit menu items in Odoo as usual.

> Where is the part of the code defining the font ? I'd like to change it to my likings.

You'll find it [here](https://github.com/Openworx/backend_theme/tree/10.0/backend_theme_v10/static/src), mainly in js/ (responsivity) and less/ (styles).

Good luck.

**Comment by genvagula** [comment]
Thnx for fast response.

This was what i meant:
(link to pic) http://d.pr/i/1nGa

Ok, i'll go and google around on how to add and edit menu items in Odoo :)
In default theme they magically appeared there and haven't really dig into that more before.

Solved the font issue. Thnx !

**Comment by Yakulu** [comment]
> This was what i meant

In backend theme, top menus items are in app view with icons. Secondary menus (in left in standard theme) take places into the top zone. *Discuss* top menu is empty because there is no secondary menu in Discuss app.

For technical information about menu items creation, see the [official documentation](https://www.odoo.com/documentation/10.0/howtos/backend.html#actions-and-menus). Note that you can also edit menus from backend interface, after activating developer mode (in Settings App), then *Settings > Technical > User Interface > Menu Items*.

**Comment by genvagula** [comment]
Thanks a lot. Will dig into this.
